### ISSUE TITLE
Feature Request: YM2151 timer and IRQ support

### ISSUE THREAD

**Issue by ZeroByteOrg** [indigodarkwolf/box16#25]
The YM2151 routines do not clock the timers, and the IRQ line is not connected to the system yet. Per Kevin (TexElec), the IRQ line is indeed connected, so it would be beneficial to activate these timers in the emulation. Furthermore, the chip also has a purely internal feature CSM which causes a keyDn event on all 8 channels whenever TimerA overflows, which does not function properly unless the timers are clocked.

**Comment by indigodarkwolf** [comment]
2ac9ed43f0c4842c88d4398e849ea06706cfa80d should implement these, and is part of the nr39.2 release. Or just get latest, a bunch of additional performance improvements have gone in as well.

I'm going to go ahead and preemptively close this, but please don't hesitate to re-open if you find a problem with the YM timers or IRQ implementation. Closing is just an organizational tool, not an ultimatum. :)
