### ISSUE TITLE
Writing to VIA IFR doesn't clear the set bits

### ISSUE THREAD

**Issue by Yazwh0** [indigodarkwolf/box16#58]
When writing to IFR, it should clear any bits that are set in the write. (bar bit 7, which should be preserved)

![image](https://user-images.githubusercontent.com/90315107/197401842-8759b252-1544-4671-bc6c-c78aaed63046.png)

This disables VIA interrupts, and then should clear the bits.

10 poke $9f0e, $7f
20 a=peek($9f0d)
30 print a
40 poke $9f0d, a
50 print peek($9f0d)

expected:
![image](https://user-images.githubusercontent.com/90315107/197401911-52cd281e-cafa-4908-b9da-c69cdb568a0f.png)

Emulator:
![image](https://user-images.githubusercontent.com/90315107/197401934-e4b5d66c-9a53-44a1-8321-0d7f7e5e1c70.png)

**Comment by indigodarkwolf** [comment]
Yeah, looking at a datasheet for the 6522, I'm not sure why Box16 implementation only respects bits 0 and 3, and then only under certain circumstances regarding the PCR.

Reading was appears to be [a datasheet for an original C64's 6522](https://datasheetspdf.com/pdf-file/1115291/Commodore/6522/1), I think the idea comes from a table that only lists means of clearing IRQ flags by interacting with the chip subcomponent that fired the IRQ:
![image](https://user-images.githubusercontent.com/5104193/197936807-d2ac1bfa-90fd-4547-9558-d0ecf9d22f48.png)

This interpretation is supported by the documentation created by the person who wrote the current VIA implementation:
https://ayce.dev/emptyx16.html#dh---ifr---interrupt-flags-register-rw
![image](https://user-images.githubusercontent.com/5104193/197937477-e2c5c4cf-3265-4b1a-9181-36b1fa1b9fe7.png)

This [datasheet for the Rockwell 6522](https://www.princeton.edu/~mae412/HANDOUTS/Datasheets/6522.pdf), however, specifically documents the ability to clear bits directly on the IFR register:
![image](https://user-images.githubusercontent.com/5104193/197937023-36d317d4-de35-457d-9c69-5fa4a6733a3e.png)

And certainly, MAME's implementation appears to be the Rockwell interpretation. Your screencap also suggests the Rockwell version.

**Comment by indigodarkwolf** [comment]
So yeah, talking with the guy who implemented it, sounds like the implementation may be a misinterpretation of the docs. Just to be clear: The photo of the expected behavior is real hardware, right? Do you know the specific model of 6522 that's using? Or does it come from an official prototype board?
