### ISSUE TITLE
0 byte crash dump written

### ISSUE THREAD

**Issue by Yazwh0** [indigodarkwolf/box16#61]
When I encountered this error https://github.com/indigodarkwolf/box16/issues/60 Box16 wrote a 0 byte dump.bin file.

**Comment by indigodarkwolf** [comment]
Whoops, seems I left the default behavior for dump files to be "don't dump anything", which is producing empty dump files.

**Comment by indigodarkwolf** [comment]
Should be fixed with [a11ec63](https://github.com/indigodarkwolf/box16/commit/a11ec63)
