### ISSUE TITLE
Can't type at blinking cursor

### ISSUE THREAD

**Issue by atrt7** [indigodarkwolf/box16#75]
I am using Fedora Workstation 37 with Wayland and I can't type at the cursor, however I can type into ImGUI elements. If you need more information let me know. Also the program does not run without "env SDL_VIDEODRIVER=x11". Without that I get this error:

`Could not find box16.ini in the following locations:
    box16.ini
    /home/atrt7/Documents/programming/X16/box16/build/box16/box16.ini
    /home/atrt7/.local/share/Box16/Box16/box16.ini
Using rom at /home/atrt7/Documents/programming/X16/x16-rom-r41/build/x16/rom.bin
    -rom sourced from: Command-line parameter
 INFO: Audio buffer is 1024 bytes
Unable to initialize GL: Unknown error
box16: ../src/imgui/imgui_impl_opengl2.cpp:114: void ImGui_ImplOpenGL2_NewFrame(): Assertion bd != __null && "Did you call ImGui_ImplOpenGL2_Init()?"' failed.
Aborted (core dumped)`

**Comment by indigodarkwolf** [comment]
Fixing the OpenGL implementation to support Wayland is going to take a while.

Meanwhile, my memory has been kickstarted by one of the other Discord users and the typing issue is probably a result of using the r41 rom with the latest source code for Box16. While the README does say that this *might* work, it also says that this is not guaranteed. In particular, after the r41 rom, several breaking changes went in and Box16 had to make changes to accommodate it. Please build the latest rom source and try again.

**Comment by indigodarkwolf** [comment]
Actually, you don't technically need to build the rom yourself, new builds are created automatically when folks make changes to the rom. As of this writing, the latest rom can be downloaded at https://github.com/commanderx16/x16-rom/actions/runs/3866296501.

**Comment by indigodarkwolf** [comment]
If you've managed to get the latest rom working (either built yourself or grabbed the build target), would you be willing to try the latest source code of Box16 to see if it resolves the other issue you had with Wayland and needing to set that environment variable?

**Comment by indigodarkwolf** [comment]
As fate would have it, things transpired that freed up a bunch of space in my home office. Which also means I could dust off one of my old PCs. A PC that now runs Fedora 37, and Wayland, and I've been able to verify that Box16 now runs correctly on a basic install that seems to be using Wayland. (`echo $XDG_SESSION_TYPE` prints `wayland`).
