### ISSUE TITLE
Tile Visualizer crashes the emulator

### ISSUE THREAD

**Issue by Yazwh0** [indigodarkwolf/box16#76]
See here:

![box16crash](https://user-images.githubusercontent.com/90315107/212468843-e4faf478-80b7-4443-b024-3d1797d7378b.gif)

**Comment by indigodarkwolf** [comment]
Confirmed on nr41.0, but appears to be fixed in nr41.1. Try grabbing the latest zip file in [Releases](https://github.com/indigodarkwolf/box16/releases).

**Comment by indigodarkwolf** [comment]
(nr41.1 should still support the same r41 rom as nr41.0)

**Comment by indigodarkwolf** [comment]
Haven't heard about this in a long time, closing. Please re-open if this recurs.
