### ISSUE TITLE
wai doesn't appear to wait for an interrupt

### ISSUE THREAD

**Issue by Yazwh0** [indigodarkwolf/box16#77]
`wai` doesn't appear to wait for an interrupt. If I enable only the vsync the attached .prg should draw one dot every frame, so slowly draw a line from 0,0. (The colour is the value of ISR.) So should be $01 (vsync) + $08 (aflow)

In the emulator as `wai` is not held, the image is all $08 apart from the one tick where vsync is set. I've included a second .prg where there is no `wai`, and the output is the same indicating that it is not actually doing anything.

[example.zip](https://github.com/indigodarkwolf/box16/files/10420857/example.zip)

(copied from the x16 emulator)

**Comment by indigodarkwolf** [comment]
On latest code, I believe Box16 is behaving correctly with regards to WAI. There may have been some fix that went into Box16 that was never ported back to x16emu.

**Comment by Yazwh0** [comment]
Yeah, sorry, jsut saw that.
