### ISSUE TITLE
error in (absolute) path handling

### ISSUE THREAD

**Issue by irmen** [indigodarkwolf/box16#8]
I've observed a problem in the path handling when attempting to load a program with `-prg`.
It seems as if it prepends `./` to the path, if it's not relative:

```irmen@neptune  ➤  ls ~/Downloads/spinner.prg 
/home/irmen/Downloads/spinner.prg
irmen@neptune  ➤  ./box16/box16 -prg ~/Downloads/spinner.prg 
Cannot open .//home/irmen/Downloads/spinner.prg!
irmen@neptune  ➤  ./box16/box16 -prg /home/irmen/Downloads/spinner.prg 
Cannot open .//home/irmen/Downloads/spinner.prg!
```

It works fine if you supply a relative path.
This is on Manjaro/Arch Linux.

**Comment by indigodarkwolf** [comment]
Latest code should have this fixed. If it looks good to you, feel free to close this.

**Comment by irmen** [comment]
yup, it works now. Thanks
