### ISSUE TITLE
Add the ability to load symbols with a rom \ ram bank

### ISSUE THREAD

**Issue by Yazwh0** [indigodarkwolf/box16#84]
If multiple symbol files are loaded, especially the ones from the ROM, the symbols can overlap giving confusing disassembly.

eg: this is in the keyb bank (1), but can see labels for basic and other banks.
![image](https://user-images.githubusercontent.com/90315107/222987022-16abea50-31dc-4f9d-ae55-af38f40ad802.png)

**Comment by indigodarkwolf** [comment]
The GUI has long supported this, I'm pretty sure the support goes all the way back to the beginning of Box16, though I know `-stds` initially loaded everything into bank 0. I did notice that the command-line `-sym` didn't support this, though, so now it does. :3 Using the same comma-separated convention as other command-line options. 

Example syntax: ./box16 -sym basic.sym,4

This loads the VICE label file "basic.sym", assigning any banked memory addresses to bank 4, so the labels won't show up or match the addresses of other banks.
